name: '"30 min" IIAB test install raspios 12'
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/ci-cd/github-actions/triggers.html
on: [push, pull_request, workflow_dispatch]

# on:
#   push:
#
#   pull_request:
#
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
#
#   # Set your workflow to run every day of the week from Monday to Friday at 6:00 UTC
#   schedule:
#     - cron: "0 6 * * 1-5"

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [raspios12] #[zero_raspbian, zero_raspios, zero2_raspios, aarch64]
        include:
        #- arch: zero_raspbian
        #  cpu: arm1176
        #  cpu_info: cpuinfo/raspberrypi_zero_w
        #  base_image: raspbian_lite:latest
        #- arch: zero_raspios
        #  cpu: arm1176
        #  cpu_info: cpuinfo/raspberrypi_zero_w
        #  base_image: raspios_lite:latest
        #- arch: zero2_raspios
        #  cpu: cortex-a7
        #  cpu_info: cpuinfo/raspberrypi_zero2_w
        #  base_image: raspios_lite:latest
        - arch: raspios12
          cpu: cortex-a7
          cpu_info: cpuinfo/raspberrypi_3b
          base_image: https://raspi.debian.net/daily/raspi_3_bookworm.img.xz
    steps:
      #- run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      #- run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      #- name: Check out repository code
      - uses: actions/checkout@v3.1.0
      - uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 1024
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          copy_repository_path: /opt/iiab/iiab
          commands: |
              #test `uname -m` = ${{ matrix.arch }}
              grep Model /proc/cpuinfo
              echo "🍏 This job's status is ${{ job.status }}."
              whoami    # runner
              pwd       # /home/runner/work/iiab/iiab == $GITHUB_WORKSPACE == ${{ github.workspace }}
              apt-get update -y --allow-releaseinfo-change
              apt-get install --no-install-recommends -y git
              ls /opt/iiab/iiab
              mkdir /etc/iiab
              cp /opt/iiab/iiab/vars/local_vars_none.yml /etc/iiab/local_vars.yml
              /opt/iiab/iiab/scripts/ansible
              ./iiab-install
              cd /opt/iiab/iiab
              iiab-summary
              cat /etc/iiab/iiab_state.yml
